apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox
  namespace: sandbox
  labels:
    app.kubernetes.io/name: sandbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: sandbox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sandbox
        tags.datadoghq.com/env: local
        tags.datadoghq.com/version: latest
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: "v1.28.0"
    spec:
      containers:
        # service-a
        - name: service-a
          image: sandbox/app:latest
          imagePullPolicy: Never
          ports:
            - name: http-a
              containerPort: 8080
          livenessProbe: &probes-default
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
          readinessProbe:
            <<: *probes-default
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          resources: &default-resources
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "250m"
          env:
            - name: DD_SERVICE
              value: service-a
            - name: SERVER_PORT
              value: '8080'
            - name: GREETINGS_URLS
              value: http://localhost:8081,http://localhost:8082

        # service-b
        - name: service-b
          image: sandbox/app:latest
          imagePullPolicy: Never
          ports:
            - name: http-b
              containerPort: 8081
          livenessProbe:
            <<: *probes-default
            httpGet:
              path: /actuator/health/liveness
              port: 8081
          readinessProbe:
            <<: *probes-default
            httpGet:
              path: /actuator/health/readiness
              port: 8081
          resources:
            <<: *default-resources
          env:
            - name: DD_SERVICE
              value: service-b
            - name: SERVER_PORT
              value: '8081'
            - name: GREETINGS_URLS
              value: http://localhost:8080,http://localhost:8082

        # service-c
        - name: service-c
          image: sandbox/app:latest
          imagePullPolicy: Never
          ports:
            - name: http-c
              containerPort: 8082
          livenessProbe:
            <<: *probes-default
            httpGet:
              path: /actuator/health/liveness
              port: 8082
          readinessProbe:
            <<: *probes-default
            httpGet:
              path: /actuator/health/readiness
              port: 8082
          resources:
            <<: *default-resources
          env:
            - name: DD_SERVICE
              value: service-c
            - name: SERVER_PORT
              value: '8082'
            - name: GREETINGS_URLS
              value: http://localhost:8080,http://localhost:8081
