apiVersion: v1
kind: Service
metadata:
  name: sandbox
  namespace: sandbox
spec:
  selector:
    app.kubernetes.io/name: sandbox
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http-service
