spring:
  application:
    name: sandbox

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
  info:
    java.enabled: true
    os.enabled: true

info:
  application: ${spring.application.name}
